### ISSUE TITLE
Add metadata

### ISSUE THREAD

**Issue by newswim** [nodeschool/denton-texas#10]
Look at the BootstrapDenton repo as an example.

**Comment by Kadaaran** [comment]
Hi @newswim , can I help ? :)

**Comment by newswim** [comment]
For sure!!! I think this is the example I was talking about:

https://github.com/techmilldenton/bootstrapdenton-2017/blob/master/_includes/head.html

I lot of those things are reliant on data from Jekyll, so the things like `og:title`, `og:image` will need to be hardcoded.

**Comment by WarEnek** [comment]
@newswim 
I hope I understood you correctly?

**Comment by newswim** [comment]
Great job, thank you!!
